### ISSUE TITLE
Crashes when points array has equal values

### ISSUE THREAD

**Issue by santo74** [astronomersiva/ember-line-graph#17]
When the array with points has all equal values, e.g. [2,2,2], then the following error is thrown:

> TypeError: Cannot read property 'y' of undefined
>     at getCoordinates (addon.js:178)
>     at path (addon.js:235)
>     at Class.<anonymous> (addon.js:52)
>     at ComputedPropertyPrototype.get (ember.debug.js:19337)
>     at Object.get (ember.debug.js:24154)
>     at RootPropertyReference.compute (ember.debug.js:17295)
>     at RootPropertyReference.value (ember.debug.js:17162)
>     at ReferenceCache.initialize (ember.debug.js:772)
>     at ReferenceCache.peek (ember.debug.js:746)
>     at DynamicAttribute.flush (ember.debug.js:1157)

I created a reproducer [here](https://ember-twiddle.com/e408a13db939f8ed381e48d711179ad7?openFiles=templates.application.hbs%2C)

**Comment by astronomersiva** [comment]
Thanks for the detailed error report and reproduction @santo74! I have fixed this and released in 1.1.1.

**Comment by santo74** [comment]
@astronomersiva I can confirm 1.1.1 is working correctly.
Thanks for fixing it so fast!
